project:
  type: website

website:
  title: "mike.depalatis.net"
  navbar:
    right:
      - index.md
      - blog/index.qmd
      - resources.md
      - icon: github
        href: https://github.com/mivade
format:
  html:
    theme: cosmo
    css: styles.css
